### PR TITLE
Add support for swift-mode

### PR DESCRIPTION
**Pull request by gooichi**

### CODE REVIEW

**Comment by syohex** [comment]
This is conflicted by previous commit, so I applied your commit manually. Thanks for PR.

**Comment by gooichi** [comment]
Thx!!!

**Comment by gooichi** [comment]
Is the "swift-mode" dict format correct?

**Comment by syohex** [comment]
I suppose it looks good. Please report us if you have problems.

**Comment by syohex** [comment]
Sorry I fixed.

**Comment by gooichi** [comment]
LGTM! Thx!!!

**Pull request closed without merging**
