### PR TITLE
Quick modernization

### PR DESCRIPTION
**Pull request by dickmao**
Replace travis with github actions
Proper Caskfile
Proper Makefile with linting
Rudimentary speed comparison with company
Deprecate ac-config-default

### CODE REVIEW

**Comment by tarsius** [comment]
Thanks!

This should be split into several atomic commits.

**Comment by dickmao** [comment]
I'm afraid I cannot comply.  If this is a showstopper, I should be taken off the maintainer list.

**Comment by tarsius** [comment]
> I'm afraid I cannot comply.

Why?!

**Comment by dickmao** [comment]
To make "maintaining" worth my while, I require full freedom and no parental
oversight.  I know from your point of view, it's simply a matter of due
diligence.  I wouldn't take this cavalier stance if
the repo in question hadn't been in its moribund state for years.  I'll even
manually reopen all the issues I closed if you tell me I'm out.

**Comment by tarsius** [comment]
I wasn't looking for a "maintainer"; I was looking for a maintainer.

**Comment by dickmao** [comment]
I need explicit confirmation that I'm out.  Thanks.

**Comment by tarsius** [comment]
If the above request is too much to ask for, then yes, this is a showstopper.

**Pull request closed without merging**
