### PR TITLE
add missing C++11 keywords

### PR DESCRIPTION
**Pull request by syohex**

### CODE REVIEW

**Comment by syohex** [comment]
@m2ym Should we add preprocessor keywords to C/C++ dictionary ?

**Comment by m2ym** [comment]
@syohex How do you think?

**Comment by syohex** [comment]
It is indifferent for me.
However original dictionary file does not contain preprocessor keywords,
so I asked you.

**Comment by m2ym** [comment]
OK, let's include the preprocessor keywords.

**Comment by syohex** [comment]
Done

**Pull request merged**
