### PR TITLE
Use cl-union to prevent adding duplicated sources

### PR DESCRIPTION
**Pull request by YorkZ**

### CODE REVIEW

**Comment by YorkZ** [comment]
It's been three years after sending this PR, any update?

**Comment by tarsius** [comment]
Yes, this package doesn't really have a maintainer anyway.

I've merged this now, looks safe enough. Thanks!

I did de-randomize the whitespace a bit. :wink:

**Comment by YorkZ** [comment]
Hi @tarsius So you are not the maintainer? You made Magit so great man!

**Comment by tarsius** [comment]
No I am not. See #509.

**Pull request merged**
