### PR TITLE
Auto-complete CSS property names

### PR DESCRIPTION
**Pull request by zk-phi**
This PR implements auto-completion of CSS property `names' (in addition to values).

### CODE REVIEW

**Comment by syohex** [comment]
Sorry, late reply.

Could you tell me in more detail ? I suppose original code can get such completion in your screenshot.

**Comment by zk-phi** [comment]
`css-property` recognizes the current property key, and auto-completes its values like

- `solid` (for `border`)
- `large` (for `font-size`)
- ...

but it does not auto-complete the property key itself, like:

- `border`
- `font-size`
- ...

As far as I see, `ac-css-prefix` function requires a colon `:` before the current position

```
(defun ac-css-prefix ()
  (when (save-excursion (re-search-backward "\\_<\\(.+?\\)\\_>\\s *:[^;]*\\=" nil t))
    (setq ac-css-property (match-string 1))
    (or (ac-prefix-symbol) (point))))
```

so it seems `css-property` ac-source does not start completion before colon.

**Comment by mistkafka** [comment]
sorry, any problem with this PR? we really need this feature, please!

**Review by jcs090218 — APPROVED** [review]

**Comment by jcs090218** [comment]
@zk-phi I think there is are several conflicts to this PR. Can you resolve it? Thanks! :)

**Comment by zk-phi** [comment]
Updated, thank you for reviewing !

**Comment by jcs090218** [comment]
Merged! Thanks!

**Pull request merged**
